### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by n0thels3** [Z3NTL3/cursed-objects#3]
The script is quite good, a recommendation is that you can add HTTP/2 or 1.3 and new headers like.

Sec-Ch-Ua-Mobile:
Sec-Ch-Ua-Platform
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Sec-Fetch-User
Accept-Language
X-Forwarded-Host <spoofed>

**Comment by Z3NTL3** [comment]
> The script is quite good, a recommendation is that you can add HTTP/2 or 1.3 and new headers like.
> 
> Sec-Ch-Ua-Mobile: Sec-Ch-Ua-Platform Sec-Fetch-Dest Sec-Fetch-Mode Sec-Fetch-Site Sec-Fetch-User Accept-Language X-Forwarded-Host

Thanks for your honest review.

HTTP2 support added
**<a href="https://github.com/Z3NTL3/cursed-objects/commit/311371a9765ecdc50cec7452da281875db7c798b">View</a>**

As for your other requests, in the future we will make enhancements to the script under a different project name called Cursed Spirits. Which is a follow up project to Cursed Objects.

**Comment by n0thels3** [comment]
As soon as cursed-spirit comes out I will try it, supporting you since ACDS Panel came out.

**Comment by Z3NTL3** [comment]
> As soon as cursed-spirit comes out I will try it, supporting you since ACDS Panel came out.

Great, make sure Cursed Objects gets 100 stars by sharing it.

At 100 stars we'll release Cursed Spirits

<img src="https://media.discordapp.net/attachments/956310840464773200/1143450552706011256/image.png?width=1440&height=608">
